# -*- mode: ruby -*-
# vi: set ft=ruby :

instances = 7
box = "centos/7"
provider = "virtualbox"
path = "/ansible-machines/centos/bootstrap.sh"
name_prefix = "server0"
name_suffix = ".flexsolutions.local"
ip_prefix = "192.168.100.20"
disk_size = "20G"
memory = "1024"
cpus = "1"

Vagrant.configure("2") do |config|
    instances.times do | i |
        node_id = "#{name_prefix}#{i}"
        config.vm.define node_id do | node |
            node.vm.box = "#{box}"
            node.vm.hostname = "#{name_prefix}#{i}#{name_suffix}"
            # node.vm.disksize.size = "20GB"

            node.vm.network "private_network", ip: "#{ip_prefix}#{1}"

            node.vm.provider "#{provider}" do |vb|
                vb.name = "#{name_prefix}#{i}#{name_suffix}"
                vb.memory = "#{memory}"
            end

            node.vm.provision "shell", path: "#{path}"
        end
    end
end
